# Generated by Django 5.0.1 on 2024-01-22 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appex', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('author', models.CharField(max_length=120)),
                ('price', models.FloatField(default=0.0)),
            ],
        ),
        migrations.DeleteModel(
            name='Books',
        ),
    ]
